### ISSUE TITLE
Error on using with webpack / babel

### ISSUE THREAD

**Issue by thedanheller** [vegetableman/drag-drop-dom#1]
I'm trying to use it with webpack / babel / es2015 loader and am getting this error:

``` js
ERROR in ./~/synthetic-dom-events/init.json
Module parse failed: /Users/cin_dprates/dev/pctrl/node_modules/synthetic-dom-events/init.json Unexpected token (2:14)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:14)
    at Parser.pp$4.raise (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/Users/cin_dprates/dev/pctrl/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/Users/cin_dprates/dev/pctrl/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/Compilation.js:126:9)
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/Compilation.js:309:10
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/cin_dprates/dev/pctrl/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/node_modules/async/lib/async.js:52:16
 @ ./~/synthetic-dom-events/index.js 105:21-43

ERROR in ./~/synthetic-dom-events/types.json
Module parse failed: /Users/cin_dprates/dev/pctrl/node_modules/synthetic-dom-events/types.json Unexpected token (2:15)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:15)
    at Parser.pp$4.raise (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/cin_dprates/dev/pctrl/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/Users/cin_dprates/dev/pctrl/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/Users/cin_dprates/dev/pctrl/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/Users/cin_dprates/dev/pctrl/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/Compilation.js:126:9)
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/Compilation.js:309:10
    at /Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/cin_dprates/dev/pctrl/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/Users/cin_dprates/dev/pctrl/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
```

**Comment by thedanheller** [comment]
closing as it seems to be not related to this lib. or it might be, but I can simply add a json loader.
